# Generated by Django 4.2.24 on 2025-09-12 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absensi',
            options={'verbose_name': 'Absensi', 'verbose_name_plural': 'Absensi'},
        ),
        migrations.AlterModelOptions(
            name='kelas',
            options={'verbose_name': 'Kelas', 'verbose_name_plural': 'Kelas'},
        ),
        migrations.AlterModelOptions(
            name='kunciabsensi',
            options={'verbose_name': 'Kunci Absensi', 'verbose_name_plural': 'Kunci Absensi'},
        ),
        migrations.AlterModelOptions(
            name='siswa',
            options={'verbose_name': 'Siswa', 'verbose_name_plural': 'Siswa'},
        ),
        migrations.AlterField(
            model_name='kelas',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nama Kelas'),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='sekretaris',
            field=models.ManyToManyField(blank=True, null=True, related_name='sekretaris_kelas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='wali_kelas',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='kunciabsensi',
            unique_together={('kelas', 'date')},
        ),
    ]
