# Generated by Django 4.2.24 on 2025-11-20 00:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_absensi_options_alter_kelas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensi',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='absensi',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='sekretaris',
            field=models.ManyToManyField(blank=True, related_name='sekretaris_kelas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='wali_kelas',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wali_kelas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
