# Generated by Django 4.2.24 on 2025-11-20 02:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_absensi_created_at_absensi_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensi',
            name='by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Oleh'),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dibuat'),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Diubah'),
        ),
    ]
