# Generated by Django 4.2.24 on 2025-11-20 15:41

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_absensi_by_alter_absensi_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='kelas',
            managers=[
                ('extra_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='siswa',
            name='kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='siswas', to='main.kelas'),
        ),
    ]
