# Generated by Django 4.2.24 on 2025-11-24 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_siswa_nis_siswa_nisn_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensi',
            name='by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Oleh'),
        ),
    ]
