# Generated by Django 4.2.24 on 2025-11-26 04:50 edited by me

import django.contrib.auth.models
import django.db.models.manager
from django.db import migrations

import main.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_absensi_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absensi',
            options={'default_manager_name': 'original_objects', 'verbose_name': 'Absensi', 'verbose_name_plural': 'Absensi'},
        ),
        migrations.AlterModelOptions(
            name='kelas',
            options={'default_manager_name': 'original_objects', 'verbose_name': 'Kelas', 'verbose_name_plural': 'Kelas'},
        ),
        migrations.AlterModelOptions(
            name='kunciabsensi',
            options={'default_manager_name': 'original_objects', 'verbose_name': 'Kunci Absensi', 'verbose_name_plural': 'Kunci Absensi'},
        ),
        migrations.AlterModelOptions(
            name='siswa',
            options={'default_manager_name': 'original_objects', 'verbose_name': 'Siswa', 'verbose_name_plural': 'Siswa'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'default_manager_name': 'original_objects'},
        ),
        migrations.AlterModelManagers(
            name='absensi',
            managers=[
                ('original_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='kelas',
            managers=[
                ('original_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='kunciabsensi',
            managers=[
                ('original_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='siswa',
            managers=[
                ('original_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', main.models.base.CustomUserManager()),
                ('original_objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
