# Generated by Django 4.2.24 on 2025-11-25 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_absensi_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
