# Generated by Django 4.2.24 on 2025-11-26 04:50 edited by me

from django.db import migrations

import main.models.base


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_alter_absensi_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="absensi",
            options={"verbose_name": "Absensi", "verbose_name_plural": "Absensi"},
        ),
        migrations.AlterModelOptions(
            name="kelas",
            options={"verbose_name": "Kelas", "verbose_name_plural": "Kelas"},
        ),
        migrations.AlterModelOptions(
            name="kunciabsensi",
            options={
                "verbose_name": "Kunci Absensi",
                "verbose_name_plural": "Kunci Absensi",
            },
        ),
        migrations.AlterModelOptions(
            name="siswa",
            options={"verbose_name": "Siswa", "verbose_name_plural": "Siswa"},
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", main.models.base.CustomUserManager()),
            ],
        ),
    ]
