# Generated by Django 4.2.24 on 2025-11-25 10:50

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import main.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_user_options_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absensi',
            options={'default_manager_name': 'original_objects', 'verbose_name': 'Absensi', 'verbose_name_plural': 'Absensi'},
        ),
        migrations.AlterModelOptions(
            name='kelas',
            options={'default_manager_name': 'original_objects', 'verbose_name': 'Kelas', 'verbose_name_plural': 'Kelas'},
        ),
        migrations.AlterModelOptions(
            name='kunciabsensi',
            options={'default_manager_name': 'original_objects', 'verbose_name': 'Kunci Absensi', 'verbose_name_plural': 'Kunci Absensi'},
        ),
        migrations.AlterModelOptions(
            name='siswa',
            options={'default_manager_name': 'original_objects', 'verbose_name': 'Siswa', 'verbose_name_plural': 'Siswa'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'default_manager_name': 'original_objects'},
        ),
        migrations.AlterModelManagers(
            name='absensi',
            managers=[
                ('original_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='kelas',
            managers=[
                ('original_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='kunciabsensi',
            managers=[
                ('original_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='siswa',
            managers=[
                ('original_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', main.models.base.CustomUserManager()),
                ('original_objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_domain', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='absensi',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='main.domain'),
        ),
        migrations.AddField(
            model_name='kelas',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='main.domain'),
        ),
        migrations.AddField(
            model_name='kunciabsensi',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='main.domain'),
        ),
        migrations.AddField(
            model_name='siswa',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='main.domain'),
        ),
        migrations.AddField(
            model_name='user',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='main.domain'),
        ),
    ]
