# Generated by Django 4.2.24 on 2025-11-25 01:34
# Beberapa kode migrasi dihapus untuk menyesuaikan

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_user_options_alter_user_managers'),
    ]

    operations = []