# Generated by Django 5.2.9 on 2025-12-04 03:07

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_alter_absensi_options_alter_kelas_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="absensi", old_name="status", new_name="_status"
        ),
        migrations.AlterField(
            model_name="absensi",
            name="_status",
            field=models.CharField(
                choices=[
                    ("hadir", "Hadir"),
                    ("sakit", "Sakit"),
                    ("izin", "Izin"),
                    ("alfa", "Alfa"),
                    ("bolos", "Bolos"),
                ],
                max_length=30,
                null=True,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="absensi",
            name="wait_expired_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[
                    ("wali_kelas", "Wali Kelas"),
                    ("kesiswaan", "Kesiswaan"),
                    ("sekretaris", "Sekretaris"),
                    ("guru_piket", "Guru Piket"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="absensi",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("_status", "wait"), _negated=True),
                    ("wait_expired_at__isnull", False),
                    _connector="OR",
                ),
                name="wait_expired_at_must_not_null_while_status_is_wait",
            ),
        ),
        migrations.AddField(
            model_name="absensi",
            name="_final_status",
            field=models.GeneratedField(
                choices=[
                    ("hadir", "Hadir"),
                    ("sakit", "Sakit"),
                    ("izin", "Izin"),
                    ("alfa", "Alfa"),
                    ("bolos", "Bolos"),
                    ("tunggu", "Menunggu"),
                ],
                db_persist=False,
                expression=models.Case(
                    models.When(
                        models.Q(("_status", "tunggu"), _negated=True),
                        then=models.F("_status"),
                    ),
                    models.When(
                        then=models.Value("bolos"),
                        wait_expired_at__gt=django.db.models.functions.datetime.Now(),
                    ),
                    default=models.Value("tunggu"),
                ),
                output_field=models.CharField(),
                verbose_name="Status",
            ),
        ),
    ]
