# Generated by Django 4.2.24 on 2025-11-25 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_user_options_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_domain', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='absensi',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='main.domain'),
        ),
        migrations.AddField(
            model_name='kelas',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='main.domain'),
        ),
        migrations.AddField(
            model_name='kunciabsensi',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='main.domain'),
        ),
        migrations.AddField(
            model_name='siswa',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='main.domain'),
        ),
        migrations.AddField(
            model_name='user',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='main.domain'),
        ),
    ]
