# Generated by Django 5.2.9 on 2025-12-05 03:15

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_absensi_status_absensi__status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsensiSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senin', models.BooleanField(default=False)),
                ('selasa', models.BooleanField(default=False)),
                ('rabu', models.BooleanField(default=False)),
                ('kamis', models.BooleanField(default=False)),
                ('jumat', models.BooleanField(default=False)),
                ('sabtu', models.BooleanField(default=False)),
                ('jam_masuk', models.TimeField()),
                ('jam_keluar', models.TimeField()),
                ('kelas', models.ManyToManyField(related_name='jadwal_kelas', to='main.kelas')),
            ],
            options={
                'verbose_name': 'Jadwal Absensi (QR)',
                'verbose_name_plural': 'Jadwal Absensi (QR)',
                'default_manager_name': 'original_objects',
            },
            managers=[
                ('original_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
