# Generated by Django 5.2.9 on 2025-12-05 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_absensisession'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensisession',
            name='jam_keluar_mulai_absen',
            field=models.TimeField(blank=True, null=True, verbose_name='Jam Pulang (Absen Pulang Dimulai)'),
        ),
        migrations.AddField(
            model_name='absensisession',
            name='jam_masuk_toleransi',
            field=models.DurationField(default=datetime.timedelta(seconds=900), verbose_name='Waktu Toleransi Masuk'),
        ),
        migrations.AlterField(
            model_name='absensisession',
            name='jam_keluar',
            field=models.TimeField(verbose_name='Jam Keluar'),
        ),
        migrations.AlterField(
            model_name='absensisession',
            name='jam_masuk',
            field=models.TimeField(verbose_name='Jam Masuk (Absen Dimulai)'),
        ),
    ]
