# Generated by Django 5.2.9 on 2025-12-12 01:35

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_absensisession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sekolah', models.CharField(max_length=100)),
                ('logo_sekolah', models.ImageField(blank=True, null=True, upload_to='')),
                ('deskripsi_sekolah', models.TextField(blank=True, null=True)),
                ('kop_sekolah', models.ImageField(blank=True, null=True, upload_to='')),
                ('nama_aplikasi', models.CharField(default='Presensee', max_length=50)),
            ],
            options={
                'verbose_name': 'Data Sekolah',
                'verbose_name_plural': 'Data Sekolah',
                'default_manager_name': 'original_objects',
            },
            managers=[
                ('original_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
