# Generated by Django 5.2.9 on 2025-12-05 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_absensisession_jam_keluar_mulai_absen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absensi',
            name='_final_status',
        ),
    ]
