# Generated by Django 5.2.9 on 2025-12-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_data_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensisession',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
