# Generated by Django 5.2.9 on 2025-12-17 09:17

import datetime
import django.db.models.manager
import main.models.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_absensisession_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'default_manager_name': 'original_objects', 'verbose_name': 'Pengguna', 'verbose_name_plural': 'Pengguna'},
        ),
        migrations.AddField(
            model_name='siswa',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.models.random_filename),
        ),
        migrations.AlterField(
            model_name='data',
            name='kop_sekolah',
            field=models.ImageField(blank=True, help_text='* Gunakan gambar format webp untuk kop sekolah', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.models.random_filename),
        ),
        migrations.CreateModel(
            name='AbsensiSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('senin', models.BooleanField(default=False)),
                ('selasa', models.BooleanField(default=False)),
                ('rabu', models.BooleanField(default=False)),
                ('kamis', models.BooleanField(default=False)),
                ('jumat', models.BooleanField(default=False)),
                ('sabtu', models.BooleanField(default=False)),
                ('jam_masuk', models.TimeField(verbose_name='Jam Masuk (Absen Dimulai)')),
                ('jam_masuk_toleransi', models.DurationField(default=datetime.timedelta(seconds=900), verbose_name='Waktu Toleransi Masuk')),
                ('jam_keluar_mulai_absen', models.TimeField(blank=True, null=True, verbose_name='Jam Pulang (Absen Pulang Dimulai)')),
                ('jam_keluar', models.TimeField(verbose_name='Jam Keluar')),
                ('kelas', models.ManyToManyField(related_name='jadwal_kelas', to='main.kelas')),
            ],
            options={
                'verbose_name': 'Jadwal Absensi (QR)',
                'verbose_name_plural': 'Jadwal Absensi (QR)',
                'default_manager_name': 'original_objects',
            },
            managers=[
                ('original_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
