# Generated by Django 5.2.9 on 2025-12-12 02:10

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_absensisession_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'default_manager_name': 'original_objects', 'verbose_name': 'Pengguna', 'verbose_name_plural': 'Pengguna'},
        ),
        migrations.AddField(
            model_name='siswa',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='absensisession',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
