# Generated by Django 5.2.9 on 2026-01-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_user_options_siswa_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nama Lengkap'),
        ),
    ]
